import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { createHash } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";

export interface ObjectStorage {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

/** Keys are generated by the platform; still refuse anything that could escape its prefix */
function assertKey(key: string): void {
  if (!/^[A-Za-z0-9/_.-]+$/.test(key) || key.includes("..") || key.startsWith("/"))
    throw new Error(`Invalid storage key: ${key}`);
}

/** Development and tests: files under a directory */
export class LocalStorage implements ObjectStorage {
  constructor(private readonly root: string) {}

  private file(key: string): string {
    assertKey(key);
    return path.join(this.root, key);
  }

  async put(key: string, body: Buffer, _contentType?: string): Promise<void> {
    const file = this.file(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, body);
  }

  get(key: string): Promise<Buffer> {
    return readFile(this.file(key));
  }

  async delete(key: string): Promise<void> {
    await rm(this.file(key), { force: true });
  }
}

/** Production: any S3-compatible store (AWS S3, GCS interoperability, Cloudflare R2, MinIO) */
export class S3Storage implements ObjectStorage {
  private readonly client: S3Client;

  constructor(
    private readonly bucket: string,
    opts: {
      region: string;
      endpoint?: string;
      accessKeyId?: string;
      secretAccessKey?: string;
      forcePathStyle?: boolean;
    },
  ) {
    this.client = new S3Client({
      region: opts.region,
      ...(opts.endpoint ? { endpoint: opts.endpoint } : {}),
      ...(opts.accessKeyId && opts.secretAccessKey
        ? { credentials: { accessKeyId: opts.accessKeyId, secretAccessKey: opts.secretAccessKey } }
        : {}),
      forcePathStyle: opts.forcePathStyle ?? Boolean(opts.endpoint),
    });
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    assertKey(key);
    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: key,
        Body: body,
        ContentType: contentType,
        // Integrity check end to end
        ContentMD5: createHash("md5").update(body).digest("base64"),
        ServerSideEncryption: "AES256",
      }),
    );
  }

  async get(key: string): Promise<Buffer> {
    assertKey(key);
    const res = await this.client.send(new GetObjectCommand({ Bucket: this.bucket, Key: key }));
    return Buffer.from(await res.Body!.transformToByteArray());
  }

  async delete(key: string): Promise<void> {
    assertKey(key);
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }
}

export const StorageEnvSchema = z.object({
  STORAGE_DRIVER: z.enum(["local", "s3"]).default("local"),
  STORAGE_LOCAL_DIR: z.string().default(".data/storage"),
  S3_BUCKET: z.string().optional(),
  S3_REGION: z.string().default("us-east-1"),
  S3_ENDPOINT: z.url().optional(),
  S3_ACCESS_KEY_ID: z.string().optional(),
  S3_SECRET_ACCESS_KEY: z.string().optional(),
});
export type StorageEnv = z.infer<typeof StorageEnvSchema>;

export function createStorage(env: StorageEnv, baseDir = process.cwd()): ObjectStorage {
  if (env.STORAGE_DRIVER === "s3") {
    if (!env.S3_BUCKET) throw new Error("S3_BUCKET is required when STORAGE_DRIVER=s3");
    return new S3Storage(env.S3_BUCKET, {
      region: env.S3_REGION,
      ...(env.S3_ENDPOINT ? { endpoint: env.S3_ENDPOINT } : {}),
      ...(env.S3_ACCESS_KEY_ID ? { accessKeyId: env.S3_ACCESS_KEY_ID } : {}),
      ...(env.S3_SECRET_ACCESS_KEY ? { secretAccessKey: env.S3_SECRET_ACCESS_KEY } : {}),
    });
  }
  return new LocalStorage(path.resolve(baseDir, env.STORAGE_LOCAL_DIR));
}

/** tenants/<tenant>/documents/<document>/v<version>/<safe file name> */
export function documentKey(tenantId: string, documentId: string, version: number, fileName: string): string {
  const safe =
    fileName
      .normalize("NFKD")
      .replace(/[^A-Za-z0-9._-]+/g, "_")
      .replace(/^[._]+/, "")
      .slice(-120) || "file";
  return `tenants/${tenantId}/documents/${documentId}/v${version}/${safe}`;
}
